$( document ).ready(function() {
	$('div[data-id="26619169"] div[data-role="input-row"] div[data-role="i123-input"] select').change(function() {
		$('div[data-id="31462017"] div[data-role="input-row"] input').val($('div[data-id="26619169"] div[data-role="input-row"] div[data-role="i123-input"] select').val());
	});  
$('div[data-id="26619184"] div[data-role="input-row"] div[data-role="i123-input"] select').change(function() {
		$('div[data-id="31462018"] div[data-role="input-row"] input').val($('div[data-id="26619184"] div[data-role="input-row"] div[data-role="i123-input"] select').val());
	});  
});